server:
  port: 6002
spring:
  application:
    name: eureka-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:6001/eureka/,http://eureka2:${server.port}/eureka/,http://eureka3:6003/eureka/
    fetch-registry: false
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: true # false表示关闭保护模式
  instance:
    hostname: eureka2